ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;
--SEQUENCES
CREATE SEQUENCE TEST_SEQUENCE MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

--TABLES
CREATE TABLE T_BASE_TYPES(
ID                NUMBER(19,0) NOT NULL,
T_SHORT           NUMBER(5,0) NOT NULL,
T_INTEGER         NUMBER(10,0) NOT NULL,
T_LONG            NUMBER(19,0) NOT NULL,
T_BIG_DECIMAL     NUMBER NOT NULL,
T_STRING_CHAR     CHAR(10) NOT NULL,
T_STRING_CLOB     CLOB NOT NULL,
T_STRING_VARCHAR2 VARCHAR2(255) NOT NULL,
T_STRING_SCDF     VARCHAR2(255) NOT NULL,
T_BLOB            BLOB NOT NULL,
T_TIME_STAMP      TIMESTAMP NOT NULL,
T_DATE            DATE NOT NULL,
T_BOOLEAN         NUMBER(1,0) NOT NULL);

CREATE TABLE T_JOIN
(
  ID                NUMBER(19,0) NOT NULL,
  T_BASE_TYPES_FK   NUMBER(19,0) NOT NULL,
  T_JOIN_STRING     VARCHAR2(255) NOT NULL
);

-- PK
ALTER TABLE T_BASE_TYPES ADD CONSTRAINT PK_T_BASE_TYPES PRIMARY KEY (ID);
ALTER TABLE T_JOIN ADD CONSTRAINT PK_T_JOIN PRIMARY KEY (ID);

--FK
ALTER TABLE T_JOIN ADD CONSTRAINT FK_BT
	FOREIGN KEY (T_BASE_TYPES_FK) REFERENCES T_BASE_TYPES (ID) ON DELETE CASCADE;
