--SEQUENCES
CREATE SEQUENCE H_SEQUENCE START 1;

--TABLES
CREATE TABLE ACCOUNT
(
  ID IDENTITY NOT NULL,
  TYPE SMALLINT NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  NAME_SCDF VARCHAR(128) NOT NULL,
  NOTE VARCHAR(1024)
);

CREATE TABLE ACCOUNT_ACTIVITY
(
  ID IDENTITY NOT NULL,
  ACCOUNT_FK BIGINT NOT NULL,
  TYPE SMALLINT NOT NULL,
  SUB_TYPE SMALLINT NOT NULL,
  ACTIVITY_DATE DATE NOT NULL,
  ACTIVITY_TIME TIME,
  VALUE DECIMAL NOT NULL,
  NOTE VARCHAR(1024)
);

CREATE TABLE BILL
(
  ID IDENTITY NOT NULL,
  NOTE VARCHAR(1024),
  NOTE_SCDF VARCHAR(1024),
  BILL_DATE DATE NOT NULL,
  BILL_TIME TIME
);

CREATE TABLE BILL_ACTIVITY
(
  ID IDENTITY NOT NULL,
  BILL_FK BIGINT NOT NULL,
  ACCOUNT_ACTIVITY_FK BIGINT NOT NULL
);

CREATE TABLE BILL_ITEM
(
  ID IDENTITY NOT NULL,
  BILL_FK BIGINT NOT NULL,
  NOTE VARCHAR(1024),
  VALUE DECIMAL NOT NULL
);

CREATE TABLE EXPENSE_CATEGORY
(
  ID IDENTITY NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  NAME_SCDF VARCHAR(128) NOT NULL,
  NOTE VARCHAR(1024)
);

CREATE TABLE ITEM_CATEGORY
(
  ID IDENTITY NOT NULL,
  BILL_ITEM_FK BIGINT NOT NULL,
  EXPENSE_CATEGORY_FK BIGINT NOT NULL
);

CREATE TABLE H_PROPERTIES
(
  ID VARCHAR(128) NOT NULL,
  VALUE VARCHAR(256) NOT NULL
);

--FK
ALTER TABLE ACCOUNT_ACTIVITY ADD CONSTRAINT FK_AA
    FOREIGN KEY (ACCOUNT_FK) REFERENCES ACCOUNT (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE BILL_ACTIVITY ADD CONSTRAINT FK_BABL
    FOREIGN KEY (BILL_FK) REFERENCES BILL (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE BILL_ACTIVITY ADD CONSTRAINT FK_BAAA
    FOREIGN KEY (ACCOUNT_ACTIVITY_FK) REFERENCES ACCOUNT_ACTIVITY (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ITEM_CATEGORY ADD CONSTRAINT FK_ITBI
    FOREIGN KEY (BILL_ITEM_FK) REFERENCES BILL_ITEM (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ITEM_CATEGORY ADD CONSTRAINT FK_BEC
    FOREIGN KEY (EXPENSE_CATEGORY_FK) REFERENCES EXPENSE_CATEGORY (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--INDEX
CREATE UNIQUE INDEX UQ_ACCOUNT ON ACCOUNT (NAME_SCDF ASC);
CREATE UNIQUE INDEX UQ_EXPENSE_CATEGORY ON EXPENSE_CATEGORY (NAME_SCDF ASC);
