--SEQUENCES
CREATE SEQUENCE TEST_SEQUENCE START 1;

--TABLES
CREATE TABLE T_BASE_TYPES
(
  ID                IDENTITY NOT NULL,
  T_SHORT_SMALLINT  SMALLINT NOT NULL,
  T_SHORT_TINYINT   TINYINT NOT NULL,
  T_INTEGER         INT NOT NULL,
  T_LONG            BIGINT NOT NULL,
  T_BIG_DECIMAL     DECIMAL NOT NULL,
  T_STRING          VARCHAR NOT NULL,
  T_STRING_SCDF     VARCHAR NOT NULL,
  T_BLOB            BLOB NOT NULL,
  T_TIME_STAMP      TIMESTAMP NOT NULL,
  T_TIME            TIME NOT NULL,
  T_DATE            DATE NOT NULL,
  T_BOOLEAN         BOOLEAN NOT NULL
);

CREATE TABLE T_JOIN
(
  ID                IDENTITY NOT NULL,
  T_BASE_TYPES_FK   BIGINT NOT NULL,
  T_JOIN_STRING     VARCHAR NOT NULL
);

--FK
ALTER TABLE T_JOIN ADD CONSTRAINT FK_BT
    FOREIGN KEY (T_BASE_TYPES_FK) REFERENCES T_BASE_TYPES (ID) ON DELETE CASCADE ON UPDATE CASCADE;
